### ISSUE TITLE
Cannot read properties of undefined (reading 'apply')

### ISSUE THREAD

**Issue by bvreddy10** [VenkateshMogili/redux-biolerplate#21]
![image](https://user-images.githubusercontent.com/29379861/185308878-daede8a6-63f4-4318-94e3-582bf75fe2cd.png)

Please solve this issue

**Comment by VenkateshMogili** [comment]
@bvreddy10 , thank you raising the issue. Due to latest redux update, createStore is deprecated. So, use legacy_createStore as createStore import, so that it works fine. check the changes in the below commit url. Thank you.

https://github.com/VenkateshMogili/redux-biolerplate/blob/f8c3dfa21a9081854520e8f324a7bcb2e7061f5e/src/store.js
